use_frameworks!

platform :ios, '8.0'

target 'DLCustomKeyBoard_Example' do
  pod 'DLCustomKeyBoard', :path => '../'

  target 'DLCustomKeyBoard_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
